package co.learn.app.entities;

import jakarta.persistence.*;
import lombok.Data;
import java.util.List;

@Entity
@Data
@Table(name = "courses")
public class Course {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String title;
    @Column(columnDefinition = "TEXT")
    private String description;
    private String language; // "fr" or "en"
    private String level; // "Débutant", etc.
    private String icon; // e.g. "code", "business"
    private String category; // e.g. "Data Science", "Design"

    @OneToMany(cascade = CascadeType.ALL)
    private List<Module> modules;

    private boolean isCompleted = false; // Tracks if the course is fully finished
    private boolean aiGenerated = false; // Tracks if the course was generated by AI

    @ManyToOne
    private User creator;

    @ManyToOne
    private User originalCreator; // The actual professor, preserved during cloning

    // STATS
    private int enrolledCount = 0;
    private double averageRating = 0.0;
    private int ratingCount = 0;

    private Long originalCourseId; // Link to the parent course for aggregating stats
}
